name: Building Dump

on: [push]

env:
  ROM_URL: https://download.c.realme.com/osupdate/RMX2001_11_OTA_0530_all_O8r4mG5RmLFG.ozip
  TZ: Asia/Kolkata
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Clone Dumper Source Code
         run: git clone https://github.com/AndroidDump/dumper
       
       - name: Setting up Dumper requirements
         run: |
              sudo chmod -R 777 dumper
              cd dumper
              sudo pip3 install wheel setuptools
              sudo bash setup.sh
              touch .tgtoken
              echo "${{ secrets.BOT }}" >> ".tgtoken"

       - name: Download Stock Rom & Generate dump
         run: |
              cd dumper
              sudo bash dumpyara.sh $ROM_URL ${{ secrets.GHTOKEN }}
       
      
    
