name: Building Dump

on: [push]

env:
  ROM_URL: https://otafsg1.h2os.com/patch/amazone2/GLO/OnePlus5TOxygen/OnePlus5TOxygen_43.J.69_GLO_069_2010292144/OnePlus5TOxygen_43_OTA_069_all_2010292144_de4a6fa.zip
  TZ: Asia/Kolkata
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Initializing environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget expect p7zip-full p7zip-rar

       - name: Clone Dumper Source Code
         run: git clone https://github.com/AndroidDumps/dumpyara
       
       - name: Setting up Dumper requirements
         run: |
              sudo chmod -R 777 dumpyara
              cd dumpyara
              pip install wheel setuptools
              sudo bash setup.sh

       - name: Download Stock Rom & Generate dump
         run: |
              cd dumpyara
              sudo bash dumpyara.sh $ROM_URL ${{ secrets.GHTOKEN }}
       
      
    
