name: Building Dump

on:
  push:
    branches: [ main ]
    paths-ignore: 'README.md'
  workflow_dispatch:

env:
  ROM_URL: https://otafsg1.h2os.com/patch/amazone2/GLO/OnePlus5TOxygen/OnePlus5TOxygen_43.J.69_GLO_069_2010292144/OnePlus5TOxygen_43_OTA_069_all_2010292144_de4a6fa.zip
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Clone Dumper Source Code
         run: git clone https://github.com/AndroidDump/dumper
       
       - name: Setting up Dumper requirements
         run: |
              sudo chmod -R 777 dumper
              cd dumper
              sudo pip3 install wheel setuptools
              sudo bash setup.sh
              touch .tg_token
              echo "${{ secrets.BOT }}" >> ".tg_token"
              touch .github_orgname
              echo "AndroidDump" >> ".github_orgname"
              touch .github_token
              echo "${{ secrets.GHTOKEN }}" >> ".github_token"
              git config --global user.email "manofuranium@gmail.com"
              git config --global user.name "ElytrA8"
       - name: Download Stock Rom & Generate dump
         run: |
              cd dumper
              sudo bash dumper.sh $ROM_URL
       
      
    
