name: Building Dump

on:
  push:
    branches: [ main ]
    paths-ignore: 'README.md'
  workflow_dispatch:

env:
  ROM_URL: http://otafsg-cost.realmemobile.com/RMX2151/RMX2151PU_11.A.83_0830_202101281938/patch/amazone2/GLO/RMX2151PU/RMX2151PU_11.A.83_0830_202101281938/RMX2151PU_11_OTA_0830_all_AFFrwZpAzh0Z_7cdab0c341af0e.ozip
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Clone Dumper Source Code
         run: git clone https://github.com/AndroidDump/dumper
       
       - name: Setting up Dumper requirements
         run: |
              sudo chmod -R 777 dumper
              cd dumper
              sudo pip3 install wheel setuptools
              sudo bash setup.sh
              touch .tg_token
              echo "${{ secrets.BOT }}" >> ".tg_token"
              touch .github_orgname
              echo "AndroidDump" >> ".github_orgname"
              touch .github_token
              echo "${{ secrets.GHTOKEN }}" >> ".github_token"
              git config --global user.email "manofuranium@gmail.com"
              git config --global user.name "ElytrA8"
       - name: Download Stock Rom & Generate dump
         run: |
              cd dumper
              sudo bash dumper.sh $ROM_URL
       
      
    
