name: Building Dump

on: [push]

env:
  ROM_URL: http://otafsg-cost.realmemobile.com/RMX1851/RMX1851EX_11.C.10_1100_202011102122/patch/amazone2/GLO/RMX1851EX/RMX1851EX_11.C.10_1100_202011102122/RMX1851EX_11_OTA_1100_all_afysQxXkAd0p_ed2a.ozip
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Clone Dumper Source Code
         run: git clone https://github.com/AndroidDump/dumper
       
       - name: Setting up Dumper requirements
         run: |
              sudo chmod -R 777 dumper
              cd dumper
              sudo pip3 install wheel setuptools
              sudo bash setup.sh
              touch .tgtoken
              echo "${{ secrets.BOT }}" >> ".tgtoken"

       - name: Download Stock Rom & Generate dump
         run: |
              cd dumper
              sudo bash dumpyara.sh $ROM_URL ${{ secrets.GHTOKEN }}
       
      
    
