name: Building Dump

on: [push]

env:
  ROM_URL: https://download.zteusa.com/products/axon-10-pro/ZTE_Axon10Pro_V2.0.0B06_SD.zip
  TZ: Asia/Kolkata
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Initializing environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget expect p7zip-full p7zip-rar

       - name: Clone Dumper Source Code
         run: git clone https://github.com/AndroidDump/dumper
       
       - name: Setting up Dumper requirements
         run: |
              sudo chmod -R 777 dumper
              cd dumper
              sudo pip3 install wheel setuptools
              sudo bash setup.sh
              touch .tgtoken
              echo "${{ secrets.BOT }}" >> ".tgtoken"

       - name: Download Stock Rom & Generate dump
         run: |
              cd dumper
              sudo bash dumpyara.sh $ROM_URL ${{ secrets.GHTOKEN }}
       
      
    
