name: Building Dump

on:
  push:
    branches: [ main ]
    paths-ignore: 'README.md'
  workflow_dispatch:

env:
  ROM_URL: http://bigota.d.miui.com/V12.1.5.0.RGICNXM/miui_PICASSO_V12.1.5.0.RGICNXM_93d47d6f82_11.0.zip
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Clone Dumper Source Code
         run: git clone https://github.com/AndroidDump/dumper
       
       - name: Setting up Dumper requirements
         run: |
              sudo chmod -R 777 dumper
              cd dumper
              sudo pip3 install wheel setuptools
              sudo bash setup.sh
              touch .tg_token
              echo "${{ secrets.BOT }}" >> ".tg_token"
              touch .github_orgname
              echo "AndroidDump" >> ".github_orgname"
              touch .github_token
              echo "${{ secrets.GHTOKEN }}" >> ".github_token"
              git config --global user.email "manofuranium@gmail.com"
              git config --global user.name "ElytrA8"
       - name: Download Stock Rom & Generate dump
         run: |
              cd dumper
              sudo bash dumper.sh $ROM_URL
       
      
    
